name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '29 7 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "This issue is stale, and has been labeled as such"
        stale-pr-message: "This pull request is stale, and has been labeled as such"
        stale-issue-label: "no-issue-activity"
        stale-pr-label: "no-pr-activity"
